### ISSUE TITLE
Make timing information optional

### ISSUE THREAD

**Issue by brianpm** [Isaaciwd/Cloud-Regimes#1]
Just looking at `simple_cluster_and_analyze.py` and I think:

1. `perf_counter` should be used instead of `time`. (e.g. https://stackoverflow.com/questions/66036844/time-time-or-time-perf-counter-which-is-faster)
2.  the timing information probably wouldn't be needed on every use, so it might be better if the timers were optional. One possibility is to incorporate them into a logger (e.g. https://realpython.com/python-timer/#adding-more-convenience-and-flexibility)

**Comment by Isaaciwd** [comment]
Hey Brian,

That’s good to know about perf_counter, I’ve always used time.time() to time code, but seems like perf counter is a better option. I plan on taking out all that timing, and a lot of the unnecessary print statements that are in there. I probably should have left TODOs for those.

Glad you got a chance to take a look,
Isaac

**Comment by Isaaciwd** [comment]
This issue has been taken care of
